#LDFLAGS=-Map=system.map
ASMKFLAGS = -I include/ -m32
LDFLAGS = -m elf_i386
CFLAGS = -m32 -fno-builtin -fno-stack-protector
CFLAGS += -I include/ -I $(BASE)/include/ -I $(BASE)/arch/$(ARCH)/include/ -I $(BASE)/arch/$(ARCH)/
Q=@

